"""生成完整可导入的 Clash Meta all.yaml。"""

from __future__ import annotations

import logging
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import yaml

from src.geo import is_europe
from src.models import Node

logger = logging.getLogger(__name__)


def _cc_in(codes: set[str]) -> Callable[[Node], bool]:
    codes_u = {c.upper() for c in codes}

    def _fn(n: Node) -> bool:
        return (n.country_code or "").upper() in codes_u

    return _fn


def _is_other(n: Node) -> bool:
    cc = (n.country_code or "OTHER").upper()
    if cc in {"US", "JP", "SG", "HK", "TW", "KR"}:
        return False
    if is_europe(cc):
        return False
    return True


REGION_GROUPS: list[tuple[str, str, Callable[[Node], bool]]] = [
    ("🇺🇸 美国", "US", _cc_in({"US"})),
    ("🇯🇵 日本", "JP", _cc_in({"JP"})),
    ("🇸🇬 新加坡", "SG", _cc_in({"SG"})),
    ("🇭🇰 香港", "HK", _cc_in({"HK"})),
    ("🇹🇼 台湾", "TW", _cc_in({"TW"})),
    ("🇰🇷 韩国", "KR", _cc_in({"KR"})),
    ("🇪🇺 欧洲", "EU", lambda n: is_europe(n.country_code or "")),
    ("🌎 其他地区", "OTHER", _is_other),
]


def build_config(
    nodes: list[Node],
    *,
    mixed_port: int = 7890,
    allow_lan: bool = False,
    mode: str = "rule",
    log_level: str = "info",
    ipv6: bool = True,
    external_controller: str = "127.0.0.1:9090",
    url_test_url: str = "https://www.gstatic.com/generate_204",
    url_test_interval: int = 300,
    url_test_tolerance: int = 50,
) -> dict[str, Any]:
    proxies = [n.to_clash_proxy() for n in nodes]
    all_names = [n.name for n in nodes]

    def url_test_group(name: str, proxy_names: list[str]) -> dict[str, Any]:
        # Clash 要求 proxies 非空；空组放 DIRECT 兜底
        members = proxy_names if proxy_names else ["DIRECT"]
        return {
            "name": name,
            "type": "url-test",
            "proxies": members,
            "url": url_test_url,
            "interval": url_test_interval,
            "tolerance": url_test_tolerance,
        }

    region_group_names: list[str] = []
    proxy_groups: list[dict[str, Any]] = []

    for gname, _key, matcher in REGION_GROUPS:
        names = [n.name for n in nodes if matcher(n)]
        proxy_groups.append(url_test_group(gname, names))
        region_group_names.append(gname)

    auto_name = "⚡ 自动选择"
    proxy_groups.insert(0, url_test_group(auto_name, all_names))

    select_proxies = [auto_name, *region_group_names, "DIRECT"]
    select_proxies.extend(all_names)

    select_group = {
        "name": "🚀 节点选择",
        "type": "select",
        "proxies": select_proxies,
    }
    proxy_groups.insert(0, select_group)

    return {
        "mixed-port": mixed_port,
        "allow-lan": allow_lan,
        "mode": mode,
        "log-level": log_level,
        "ipv6": ipv6,
        "external-controller": external_controller,
        "proxies": proxies,
        "proxy-groups": proxy_groups,
        "rules": [
            "GEOIP,LAN,DIRECT",
            "MATCH,🚀 节点选择",
        ],
    }


def generate_yaml(
    nodes: list[Node],
    output_path: str | Path,
    **kwargs: Any,
) -> dict[str, Any]:
    cfg = build_config(nodes, **kwargs)
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    header = (
        f"# Generated by clash-sub-builder\n"
        f"# Updated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
        f"# Nodes: {len(nodes)}\n"
    )
    body = yaml.safe_dump(
        cfg,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=120,
    )
    path.write_text(header + body, encoding="utf-8")
    logger.info("Wrote %s (%d proxies)", path, len(nodes))
    return cfg


def country_stats(nodes: list[Node]) -> dict[str, int]:
    c = Counter((n.country_code or "OTHER").upper() for n in nodes)
    return dict(sorted(c.items(), key=lambda x: (-x[1], x[0])))


def validate_yaml_file(path: str | Path) -> dict[str, Any]:
    """YAML 语法校验，返回解析后的 dict。"""
    text = Path(path).read_text(encoding="utf-8")
    data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError("all.yaml root must be a mapping")
    for key in ("proxies", "proxy-groups", "rules"):
        if key not in data:
            raise ValueError(f"missing required key: {key}")
    return data